bug(fix): create images subfolder inside downloadDir, disable dirTemplate
ImagingDataCommons/SlicerIDCBrowser pull request #37
Opened 2024-05-10 01:51 UTC by vkt1414

Addresses #36 

I do not know if the images folder inside the series folder was created on the fly previously. This PR uses Pathlib to create the images subfolder and to resolve the series download folder easily.  Secondly, the dirTemplate is set to None in both download_from_manifest and download_dicom_series.

2024-05-10 18:38 UTC, fedorov commented
> Secondly, the dirTemplate is set to None in both download_from_manifest and download_dicom_series.

@vkt1414 can you please revisit/retest this? Folder hierarchy is very helpful, and I would very much prefer to use it. I would be very surprised if this function does not do recursive import: https://github.com/ImagingDataCommons/SlicerIDCBrowser/blob/main/IDCBrowser/IDCBrowser.py#L981 !

2024-05-10 19:22 UTC, fedorov requested changes
I do not see why it should be required to have a flat file layout for the downloaded content.

2024-05-10 21:36 UTC, vkt1414 commented
> I do not see why it should be required to have a flat file layout for the downloaded content.

files are downloaded but cannot be loaded into scene.

![image](https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/115020590/0b017612-3d2d-44a6-b24f-1b4fc38910b1)

2024-05-11 11:15 UTC, fedorov commented
> cannot be loaded into scene

I don't see how this would depend on the file layout on disk.... need to debug.

2024-05-11 12:40 UTC, vkt1414 commented
> > cannot be loaded into scene
> 
> I don't see how this would depend on the file layout on disk.... need to debug. 

It's working fine on Linux but not Windows. From what I saw, it's the path of the files (forward vs backward slashes) being passed on Windows. I will try to figure it out.

2024-05-11 20:50 UTC, vkt1414 commented
I'm unable to figure out the ctk indexer on Windows

This is what it says and does not update the slicer dicom database display window. 

"DICOM indexer has successfully processed 113 files [0.05s]"
"DICOM indexer has updated display fields for 0 files [0.00s]"

2024-05-14 23:50 UTC, closed without merging

2024-05-14 23:50 UTC, vkt1414 commented
closing as #38 supersedes this

2024-05-15 18:02 UTC, fedorov commented
> files are downloaded but cannot be loaded into scene.

For the sake of completeness, this was due to a different issue:

https://discourse.slicer.org/t/windows-unable-to-import-dicom-files-that-are-in-a-onedrive-backed-up-folder/36153